### ISSUE TITLE
Article Page Layout - Desktop

### ISSUE THREAD

**Issue by tiflin** [mikeybkats/MoMM2#8]
Please see wireframes for article page layout.

[https://docs.google.com/drawings/d/1zu0TiySIydFSzQUFBvkxJE8AWIXJhUxao0hN11Ephxc/edit](url)

![screen shot 2017-08-11 at 3 35 21 pm](https://user-images.githubusercontent.com/30940080/29234277-bbbd42b4-7eaa-11e7-9ada-a67262d57210.png)

**Comment by mikeybkats** [comment]
please check again.  . I think we are basically good with layout.
